"""init

Revision ID: 7d573978e8cc
Revises: 
Create Date: 2022-06-14 13:22:00.776764

"""
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7d573978e8cc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("underlying_datetime", sa.DateTime(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("reasons", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("activity_identifier", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("associated_value", sa.String(), nullable=False),
        sa.Column("retailer", sa.String(), nullable=False),
        sa.Column("campaigns", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_activity_identifier"), "activity", ["activity_identifier"], unique=False)
    op.create_index(op.f("ix_activity_associated_value"), "activity", ["associated_value"], unique=False)
    op.create_index(op.f("ix_activity_campaigns"), "activity", ["campaigns"], unique=False)
    op.create_index(op.f("ix_activity_created_at"), "activity", ["created_at"], unique=False)
    op.create_index(op.f("ix_activity_datetime"), "activity", ["datetime"], unique=False)
    op.create_index(op.f("ix_activity_reasons"), "activity", ["reasons"], unique=False)
    op.create_index(op.f("ix_activity_retailer"), "activity", ["retailer"], unique=False)
    op.create_index(op.f("ix_activity_summary"), "activity", ["summary"], unique=False)
    op.create_index(op.f("ix_activity_type"), "activity", ["type"], unique=False)
    op.create_index(op.f("ix_activity_underlying_datetime"), "activity", ["underlying_datetime"], unique=False)
    op.create_index(op.f("ix_activity_user_id"), "activity", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_user_id"), table_name="activity")
    op.drop_index(op.f("ix_activity_underlying_datetime"), table_name="activity")
    op.drop_index(op.f("ix_activity_type"), table_name="activity")
    op.drop_index(op.f("ix_activity_summary"), table_name="activity")
    op.drop_index(op.f("ix_activity_retailer"), table_name="activity")
    op.drop_index(op.f("ix_activity_reasons"), table_name="activity")
    op.drop_index(op.f("ix_activity_datetime"), table_name="activity")
    op.drop_index(op.f("ix_activity_created_at"), table_name="activity")
    op.drop_index(op.f("ix_activity_campaigns"), table_name="activity")
    op.drop_index(op.f("ix_activity_associated_value"), table_name="activity")
    op.drop_index(op.f("ix_activity_activity_identifier"), table_name="activity")
    op.drop_table("activity")
    # ### end Alembic commands ###
