name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      LOG_FORMATTER: brief
      DATABASE_URI: "postgresql://postgres@127.0.0.1:5432/hubble_test"
      RABBIT_DSN: "amqp://guest:guest@127.0.0.1:5672/"
      REDIS_URL: redis://127.0.0.1:6379/0
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: hubble_test
          POSTGRES_HOST_AUTH_METHOD: trust
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry config http-basic.azure jeff ${{ secrets.AZURE_DEVOPS_PAT }}
      - run: poetry install
      - run: poetry run alembic upgrade head
      - run: poetry run xenon --no-assert --max-average A --max-modules B --max-absolute B .
      - run: poetry run ruff check .
      - run: poetry run mypy .
      - run: poetry run refurb hubble tests
      - run: poetry run pytest --verbose --cov hubble --cov-report term-missing
